# Generated by Django 5.1 on 2025-05-21 02:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persional',
            name='announcements',
            field=wagtail.fields.StreamField([('announcement', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.URLBlock', (), {'blank': False, 'null': False}), 3: ('wagtail.blocks.StructBlock', [[('announcement_image', 0), ('announcement', 1), ('announcement_url', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='persional',
            name='cards',
            field=wagtail.fields.StreamField([('card', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'blank': False, 'null': False}), 4: ('wagtail.blocks.StructBlock', [[('card_image', 0), ('card_title', 1), ('card_description', 2), ('card_url', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='persional',
            name='products',
            field=wagtail.fields.StreamField([('product', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.URLBlock', (), {'blank': False, 'null': False}), 3: ('wagtail.blocks.StructBlock', [[('product_image', 0), ('product_name', 1), ('product_url', 2)]], {})}),
        ),
    ]
