# Generated by Django 5.1 on 2025-05-26 16:23

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtmCityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('city_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Branch City Page',
                'verbose_name_plural': 'Branch City Pages',
                'ordering': ['city_name'],
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BranchCityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('city_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Branch City Page',
                'verbose_name_plural': 'Branch City Pages',
                'ordering': ['city_name'],
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='VisitPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Visit Us Page',
                'verbose_name_plural': 'Visit Us Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AtmLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main Street Branch', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='visitus.atmcitypage')),
            ],
            options={
                'verbose_name': 'ATM Location',
                'verbose_name_plural': 'ATM Locations',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AtmPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('item_title', models.CharField(max_length=255)),
                ('atm_icon', models.ForeignKey(blank=True, help_text='ATM Icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'ATM Page',
                'verbose_name_plural': 'ATM Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BranchesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('item_title', models.CharField(max_length=255)),
                ('branch_icon', models.ForeignKey(blank=True, help_text='Branch Icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Branches Page',
                'verbose_name_plural': 'Branches Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BranchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main Street Branch', max_length=255)),
                ('atm_machine_count', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_time', models.TextField(blank=True, null=True)),
                ('close_time', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='visitus.branchcitypage')),
            ],
            options={
                'verbose_name': 'Branch Location',
                'verbose_name_plural': 'Branch Locations',
                'ordering': ['title'],
            },
        ),
    ]
