# Generated by Django 5.1 on 2025-05-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atmpage',
            old_name='atm_icon',
            new_name='item_icon',
        ),
        migrations.RenameField(
            model_name='branchespage',
            old_name='branch_icon',
            new_name='item_icon',
        ),
    ]
