# Generated by Django 5.1 on 2025-05-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitus', '0002_rename_atm_icon_atmpage_item_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchlocation',
            name='is_available_ladies_section',
            field=models.BooleanField(default=False),
        ),
    ]
