# Generated by Django 5.1 on 2025-05-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0006_contactsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
    ]
