# Generated by Django 5.1 on 2025-05-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_us', models.CharField(default='Head Office, Kuwait City', max_length=255)),
                ('call_us', models.CharField(default='+965 1803333', max_length=255)),
                ('write_to_us', models.CharField(default='info@kfh.com', max_length=255)),
                ('intro', models.TextField(default='Kuwait Finance House is a pioneer in Islamic banking.')),
                ('about', models.CharField(default='About Kuwait Finance House', max_length=255)),
                ('reports', models.CharField(default='Financial Reports', max_length=255)),
                ('faqs', models.CharField(default='FAQs', max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('snapchat_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Footer Settings',
            },
        ),
    ]
