# Generated by Django 5.1 on 2025-05-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_us', models.CharField(max_length=255)),
                ('call_us', models.CharField(max_length=255)),
                ('write_to_us', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
                ('about', models.CharField(max_length=255)),
                ('reports', models.CharField(max_length=255)),
                ('faqs', models.CharField(max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('snapchat_url', models.URLField(blank=True)),
                ('copyright_text', models.CharField(default='COPYRIGHT © 2025 KUWAIT FINANCE HOUSE. ALL RIGHTS RESERVED', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='FooterSettings',
        ),
    ]
