# Generated by Django 5.1 on 2025-05-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_footer_call_us_icon_footer_visit_us_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='copyright_text',
            field=models.CharField(max_length=255),
        ),
    ]
