# Generated by Django 5.1 on 2025-05-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_footer_call_us_icon_alter_footer_visit_us_icon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
