# Generated by Django 5.1 on 2025-05-10 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0006_delete_footer'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_us', models.CharField(max_length=255)),
                ('call_us', models.CharField(max_length=255)),
                ('write_to_us', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
                ('about', models.CharField(max_length=255)),
                ('reports', models.CharField(max_length=255)),
                ('faqs', models.CharField(max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('snapchat_url', models.URLField(blank=True)),
                ('copyright_text', models.CharField(max_length=255)),
                ('call_us_icon', models.ForeignKey(blank=True, help_text='Call Us Icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('visit_us_icon', models.ForeignKey(blank=True, help_text='Visit Us Icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('write_to_us_icon', models.ForeignKey(blank=True, help_text='Write To Us Icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
