# Generated by Django 5.1 on 2025-05-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='call_us_icon',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='visit_us_icon',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='write_to_us_icon',
        ),
    ]
