# Generated by Django 5.1 on 2025-05-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_footer_call_us_icon_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='call_us_icon',
            field=models.ForeignKey(blank=True, help_text='Call Us Icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='footer',
            name='visit_us_icon',
            field=models.ForeignKey(blank=True, help_text='Visit Us Icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='footer',
            name='write_to_us_icon',
            field=models.ForeignKey(blank=True, help_text='Write To Us Icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
