# Generated by Django 5.1 on 2025-05-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_footer_call_us_icon_footer_visit_us_icon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
