# Generated by Django 5.1 on 2025-05-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_footer_options_footer_expire_at_footer_expired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='live',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='live_revision',
        ),
    ]
