# Generated by Django 5.1 on 2025-05-11 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_footer_expire_at_remove_footer_expired_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='snapchat_url',
        ),
        migrations.AddField(
            model_name='footer',
            name='linkedin_icon',
            field=models.ForeignKey(blank=True, help_text='LinkedIn Icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='footer',
            name='twitter_icon',
            field=models.ForeignKey(blank=True, help_text='Twitter Icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='footer',
            name='youtube_icon',
            field=models.ForeignKey(blank=True, help_text='Youtube Icon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
