# Generated by Django 5.1 on 2025-05-11 11:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_footer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='call_us',
            field=wagtail.fields.StreamField([('contact', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('country', 0), ('contact_no', 0)]], {})}, help_text='Contact Details'),
        ),
    ]
