# Generated by Django 5.1 on 2025-05-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_footer_call_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='call_us',
            new_name='contact_details',
        ),
    ]
