# Generated by Django 5.1 on 2025-05-11 11:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_call_us_footer_contact_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='contact_details',
        ),
        migrations.AddField(
            model_name='footer',
            name='contact_info',
            field=wagtail.fields.StreamField([('contact', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('country', 0), ('contact_no', 0)]], {})}, help_text='Contact Details'),
        ),
    ]
