# Generated by Django 5.1 on 2025-05-11 11:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_footer_contact_details_footer_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='footer',
            name='call_us',
            field=wagtail.fields.StreamField([('contact', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('country', 0), ('contact_no', 0)]], {})}, help_text='Contact Details'),
        ),
    ]
