# Generated by Django 5.1 on 2025-06-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_footer_contact_info_footer_call_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='footer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='footer',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='translation_key',
        ),
    ]
