# Generated by Django 5.1 on 2025-05-22 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='NewsIndexPage',
        ),
        migrations.DeleteModel(
            name='NewsPage',
        ),
    ]
