# Generated by Django 5.1 on 2025-05-22 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_newscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_pages', to='News.newscategory'),
        ),
    ]
