# Generated by Django 5.1 on 2025-05-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_rename_intro_newspage_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='short_description',
        ),
    ]
