# Generated by Django 5.1 on 2025-05-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_remove_newspage_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='short_title',
            field=models.CharField(default='Default title', max_length=255),
        ),
    ]
