# Generated by Django 5.1 on 2025-05-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blogindexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
    ]
