# Generated by Django 5.1 on 2025-05-11 15:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_blogindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='who_we_are',
            field=wagtail.fields.StreamField([('highlight', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})}, help_text='What we do'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='highlights',
            field=wagtail.fields.StreamField([('Growth', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})}, help_text='Growth'),
        ),
    ]
