# Generated by Django 5.1 on 2025-05-11 16:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_who_we_are_alter_homepage_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_page_images',
            field=wagtail.fields.StreamField([('home_page_image', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2)]], {})}),
        ),
    ]
